### PR TITLE
Adds Proper Apache License 2.0

### PR DESCRIPTION
**Pull request by crweiner**
While the README says that this repo is under the Apache License 2.0, no LICENSE file was found. 

This PR adds the proper license file to the repo in Github format and formats the LICENSE/README links to reference the license without Markdown (as in, the file is just LICENSE, not LICENSE.md) for consistency across other srd-d repos.

Don't forget to add the copyright year and name at the bottom of the license. :smile:

### CODE REVIEW

**Review by kuba-- — CHANGES_REQUESTED** [review]
Thanks, could you sign your PR?

**Comment by crweiner** [comment]
@kuba-- No problem, all commits are now signed. That took much longer than anticipated because I had to update my local verision of Git first...I made these changes on Github directly.

**Comment by kuba--** [comment]
@crweiner - actually it would be better if you modify our Makefile which updates this repo:
https://github.com/src-d/go-mysql-server/blob/master/_scripts/go-vitess/Makefile
We shouldn't take PRs to this repo (this is just a snapshot generated by our script).

**Comment by crweiner** [comment]
No problem at all, and I'm sorry that I just saw that now. 
I've mad the PR in the proper repo at https://github.com/src-d/go-mysql-server/pull/436

**Pull request closed without merging**
